name: Release

on:
    push:
        branches:
            - main
        paths-ignore:
            - CHANGELOG.md
            - README.md
            - CONTRIBUTING.md
            - renovate.json
            - ".github/workflows/**"
            - .releaserc.yml
            - .prettierrc
            - eslint.config.mjs
            - vitest.config.mts
            - codecov.yml
    workflow_dispatch:

jobs:
    test:
        name: Test
        uses: ./.github/workflows/test.yml
        secrets: inherit
    release:
        name: Release on GitHub
        runs-on: ubuntu-24.04
        env:
            TERM: dumb
        permissions:
            contents: write
            issues: write
            pull-requests: write
        needs:
            - test
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
            - name: Install dependencies
              run: npm install
            - name: Import GPG key for signing commits
              id: import-gpg
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.PGP_SECRET }}
                  passphrase: ${{ secrets.PGP_PASSPHRASE }}
                  git_config_global: true
                  git_user_signingkey: true
                  git_commit_gpgsign: true
            - name: Login to Docker Hub
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Publish on GitHub
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
                  GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
                  GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
                  GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
                  GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
                  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
                  PGP_SECRET: ${{ secrets.PGP_SECRET }}
            - name: Generate doc with typedoc
              run: npx typedoc
            - name: Publish doc on GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: docs
